server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: neo4j-crud-service
  jackson:
    serialization:
      write-dates-as-timestamps: false
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: password
  data:
    neo4j:
      database: neo4j

logging:
  level:
    com.mito.neo4j: INFO
    org.springframework: WARN
    org.neo4j.driver: WARN
    org.springframework.data.neo4j: INFO